version: "3.9"  # optional since v1.27.0

services:
  postgres:
    image: postgres:14.4-alpine
    environment:
      PGDATA: /data/postgres
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped